{{- $svcName := include "grist.doc.fullname" . -}}
{{- $component := "lb" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grist.lb.config" . }}
  labels:
    {{- include "grist.common.labels" (list . $component) | nindent 4 }}
data:
  nginx.conf.template: |
    server {
      listen 8080;

      resolver $NGINX_LOCAL_RESOLVERS valid=5s;

      location /health {
        return 200;
      }

      location ~ /dw/([0-9]*).([0-9]*).([0-9]*).([0-9]*)/(.*)$ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://$1-$2-$3-$4.{{ $svcName }}.{{ .Release.Namespace }}.svc.cluster.local:8484/$5;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }
