{{- $envVars := include "common.env.transformDict" .Values.envVars -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  serviceName: {{ $fullName }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- if $.Values.image.credentials }}
      imagePullSecrets:
        - name: {{ include "common.secret.dockerconfigjson.name" (dict "fullname" $fullName "imageCredentials" $.Values.image.credentials) }}
      {{- end}}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if $envVars}}
          env:
            {{- $envVars | indent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- if .Values.monitoring.exporter.enabled }}
            - name: metrics
              containerPort: {{ .Values.monitoring.exporter.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.probes.liveness }}
          livenessProbe:
            {{- if .Values.probes.liveness.exec }}
            exec:
            {{- toYaml .Values.probes.liveness.exec | nindent 14 }}
            {{- else if .Values.probes.liveness.tcpSocket }}
            tcpSocket:
            {{- toYaml .Values.probes.liveness.tcpSocket | nindent 14 }}
            {{- else }}
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            {{- end }}
            initialDelaySeconds: 10
            timeoutSeconds: 10
          {{- end }}
          {{- if .Values.probes.readiness }}
          readinessProbe:
            {{- if .Values.probes.readiness.exec }}
            exec:
              {{- toYaml .Values.probes.readiness.exec | nindent 14 }}
            {{- else if .Values.probes.readiness.tcpSocket }}
            tcpSocket:
            {{- toYaml .Values.probes.readiness.tcpSocket | nindent 14 }}
            {{- else }}
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            {{- end }}
            initialDelaySeconds: 10
            timeoutSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /persist
              name: {{ $fullName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{ $fullName }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
